branches:
  - main

tagFormat: v${version}

plugins:
  - "@semantic-release/commit-analyzer"
  - - "@semantic-release/release-notes-generator"
    - preset: conventionalcommits
  - - "@semantic-release/github"
    - preset: conventionalcommits
